//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Architects.Training.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toci.Architects.Training.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;01241712147&quot;
        ///&quot;88110517786&quot;
        ///&quot;66100312623&quot;
        ///&quot;15320615265&quot;
        ///&quot;61102811972&quot;
        ///&quot;03240419391&quot;
        ///&quot;24032017793&quot;
        ///&quot;75020307220&quot;
        ///&quot;37092714429&quot;
        ///&quot;87061113917&quot;
        ///&quot;50021510516&quot;
        ///&quot;81060400966&quot;
        ///&quot;01300117195&quot;
        ///&quot;05232902137&quot;
        ///&quot;75100314627&quot;
        ///&quot;00310706371&quot;
        ///&quot;08252012765&quot;
        ///&quot;68081110304&quot;
        ///&quot;64111810912&quot;
        ///&quot;65010100731&quot;
        ///&quot;53032104770&quot;
        ///&quot;19090201273&quot;
        ///&quot;19110713506&quot;
        ///&quot;03320203559&quot;
        ///&quot;85091412886&quot;
        ///&quot;75052902686&quot;
        ///&quot;21083107516&quot;
        ///&quot;38013010820&quot;
        ///&quot;92122017084&quot;
        ///&quot;09242412431&quot;
        ///&quot;09211312890&quot;
        ///&quot;68120812709&quot;
        ///&quot;23090309718&quot;
        ///&quot;94021216836&quot;
        ///&quot;8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pesel {
            get {
                return ResourceManager.GetString("pesel", resourceCulture);
            }
        }
    }
}
